[tool.poetry]
name = "tracker_project"
version = "0.1.0"
description = ""
authors = ["Filippov A. S."]
readme = "README.md"



[tool.poetry.dependencies]
python = "^3.13"
django = "^6.0.2"
djangorestframework = "^3.16.1"
pillow = "^12.1.1"
python-dotenv = "^1.2.1"
psycopg2-binary = "^2.9.11"
django-filter = "^25.2"
djangorestframework-simplejwt = "^5.5.1"
coreapi = "^2.3.3"
drf-spectacular = "^0.29.0"
stripe = "^14.4.1"
celery = "^5.6.2"
redis = "^7.3.0"
django-celery-beat = "^2.9.0"
django-cors-headers = "^4.9.0"
python-telegram-bot = "^22.7"


[tool.poetry.group.dev.dependencies]
flake8 = "^7.3.0"
black = "^26.1.0"
isort = "^8.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

