# Generated by Django 6.0.3 on 2026-03-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="telegram_chat_id",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
