# Generated by Django 6.0.2 on 2026-03-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses_and_training", "0003_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["id"],
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["id"],
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
